#+OPTIONS: \n:t

The m3ga emacs experience


#+BEGIN_VERSE
inspired by the muscle memory of common text editors and IDEs.
Kate, VSCode, Intellij, NetBeans
regular browser defaults.

also inspired by the ideas behind ergoemacs by that Xah guy, fly keys

This config is mine. it is for me.
I'm not building it with the intention to distribute.
But I have a mind for standards, so I'm excercising my freedom to develope a psuedo one, or two


elpaca packaging
    chose between package-vc-install vs straight vs use-package vs elpaca

orderless + vertico + corfu to turn minibuffer into centered floating command palette

вњ… ctrl+t :  new tab
вњ… ctrl+в†ђв†‘в†“в†’ :  jumps text
вњ… ctrl+pgup/pgdn :  tab right/left
вњ… shift+в†ђв†‘в†“в†’ :  selects text
вњ… ctrl+( :  split pane right
вњ… ctrl+) :  split pane down



рџ”і frutiger-motions
    shift: select,invert,intensify,2nd function
    alt: navigation 
    ctrl: modification,mode switching, jumping

    1D nav: в†ђв†’ в†“в†‘ ad sw ( hl jk / j; lk )
    2D nav: в†ђв†“в†‘в†’  aswd ( hjkl / jlk; ) 
    3D nav: wasdqe 
    1D navigable orders examples:
    - adjacent (visually next to, on a axis xyz. eg/ visual list of tabs,buffers in a line)
    - hierarchy (в†‘в†“filetree)
    - time (mru lru, undo redo)

рџ”і typhob-myedne navigation
    navigation paradigm that uses LRU & bounding box related scanning to reliably and deterministically
    navigate focusable rectangles in a 2d plane, ev
#+END_VERSE
    #+begin_src
    в•”в•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•—      в•”в”Џв”Ѓв”Ѓв”“в•ђв•ђв•ђв•ђв•ђв•ђв•—
    в•‘в•”в•ђв•ђв•ђв•ђв•—в•”в•ђв•ђв•—в•‘      в•‘в”—в”Ѓв”Ѓв”›в•ђв•—в•”в•ђв•ђв•—в•‘
    в•‘в•‘в•”в•—в•”в•—в•‘в•‘в•”в•—в•‘в•‘  or  в•‘в•‘в•”в•—в•”в”Џв”Ѓв”Ѓв”“в•—в•‘в•‘
    в•‘в•‘в•љв•ќв•љв•ќв•‘в•‘в•љв•ќв•‘в•‘ even в•‘в•‘в”Џв”Ѓв”Ѓв”“в”Ѓв”Ѓв”›в•ќв•‘в•‘
    в•‘в•‘в•”в•ђв•ђв•—в•‘в•‘в•”в•—в•‘в•‘      в•‘в•‘в”ѓ  в”ѓв•‘в•‘в•”в•—в•‘в•‘
    в•‘в•‘в•љв•ђв•ђв•ќв•‘в•‘в•љв•ќв•‘в•‘      в•‘в•‘в”—в”Ѓв”Ѓв”›в”Џв”Ѓв”Ѓв”“в•‘в•‘
    в•‘в•љв•ђв•ђв•ђв•ђв•ќв•љв•ђв•ђв•ќв•‘      в•‘в•љв•ђв•ђв•ђв•ђв”—в”Ѓв”Ѓв”›в•ќв•‘
    в•љв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ќ      в•љв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ђв•ќ
    #+end_src
#+BEGIN_VERSE
    
    

** Parity With KDE Kate

рџ”і XDG file picker
рџ”і unsaved buffer confirmation dialogue before quit
рџ”і unsaved buffer confirmation dialogue inhibit kde plasma shutdown
рџ”і File tree sidemenu (auto refreshing)
рџ”і code navigation sidemenu (menu of variables, functions, classes, etc)
рџ”і buffer list sidemenu
рџ”і shift+enter auto copies bullet point, non-normal leading text over to new line
рџ”і multi-cursor в†‘в†“
рџ”і (S-)tab on selection (un)indents


    
** Misc




** Potentials

рџ”і ctrl+tab triggers autocompletion, intellisense
рџ”і ctrl+esc / ctrl+space leader for keychord sequence listening
рџ”і shift+esc same as C-g (quit any keychord sequence lock)
рџ”і timed passive keychord sequence listening


** Idea

- leader opens dual fields both ( dedicated keychord sequence field & command palette )
    probs nah
#+END_VERSE
